# Generated by Django 6.0 on 2026-06-24 06:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_allow_null_dates_temporarily'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractamortizationschedule',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto de Seguro'),
        ),
        migrations.AlterField(
            model_name='contractamortizationschedule',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, help_text='Capital + Interés + Seguro', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cuota Total'),
        ),
    ]
