# Generated by Django 6.0 on 2026-06-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0023_creditsupportrequest'),
        ('tenants', '0003_create_file_resource_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditsupportrequest',
            new_name='credit_supp_active__c920bd_idx',
            old_name='credit_supp_active__idx',
        ),
        migrations.RenameIndex(
            model_name='creditsupportrequest',
            new_name='credit_supp_client__36c8e4_idx',
            old_name='credit_supp_client__idx',
        ),
        migrations.RenameIndex(
            model_name='creditsupportrequest',
            new_name='credit_supp_status_fbf63c_idx',
            old_name='credit_supp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='creditsupportrequest',
            new_name='credit_supp_request_12f62e_idx',
            old_name='credit_supp_type_st_idx',
        ),
        migrations.AlterField(
            model_name='creditsupportrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creditsupportrequest',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AlterField(
            model_name='creditsupportrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
