# Generated by Django 6.0 on 2026-06-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0024_rename_credit_supp_active__idx_credit_supp_active__c920bd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinstallment',
            name='insurance_detail',
            field=models.JSONField(blank=True, default=dict, help_text='Detalles de los seguros aplicados a esta cuota', verbose_name='Detalle de Seguro'),
        ),
    ]
