# Generated by Django 6.0 on 2026-06-24 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Si True, la suscripción se cancelará al final del período actual', verbose_name='Cancelar al Fin del Período'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_until',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la cual tiene gracia después de un pago fallido', null=True, verbose_name='Período de Gracia'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, help_text='Plan pendiente para aplicar al final del período (downgrade)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_subscriptions', to='saas.subscriptionplan', verbose_name='Plan Pendiente'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='ID del customer en Stripe', max_length=100, null=True, unique=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_latest_invoice_id',
            field=models.CharField(blank=True, help_text='ID de la última factura en Stripe', max_length=100, null=True, verbose_name='Stripe Latest Invoice ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, help_text='ID del método de pago predeterminado en Stripe', max_length=100, null=True, verbose_name='Stripe Payment Method ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_status',
            field=models.CharField(blank=True, help_text='Estado de la suscripción en Stripe', max_length=20, null=True, verbose_name='Stripe Status'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='ID de la suscripción en Stripe', max_length=100, null=True, unique=True, verbose_name='Stripe Subscription ID'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='USD', help_text='Código ISO de moneda (USD, BOB, etc.)', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_annual_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID (Anual)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_monthly_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID (Mensual)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_quarterly_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID (Trimestral)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='ID del producto en Stripe', max_length=100, null=True, unique=True, verbose_name='Stripe Product ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Período de Prueba'), ('ACTIVE', 'Activa'), ('SUSPENDED', 'Suspendida'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada'), ('PAST_DUE', 'Pago Vencido'), ('PENDING_DOWNGRADE', 'Pendiente de Downgrade'), ('PENDING_CANCELLATION', 'Pendiente de Cancelación')], default='TRIAL', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_invoice_id', models.CharField(max_length=100, unique=True, verbose_name='Stripe Invoice ID')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de Factura')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierta'), ('paid', 'Pagada'), ('void', 'Anulada'), ('uncollectible', 'Incobrable')], default='open', max_length=20, verbose_name='Estado')),
                ('invoice_pdf', models.URLField(blank=True, help_text='URL del PDF en Stripe', null=True, verbose_name='PDF de Factura')),
                ('hosted_invoice_url', models.URLField(blank=True, help_text='URL pública de la factura en Stripe', null=True, verbose_name='URL de Factura Hospedada')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de Stripe', verbose_name='Metadata')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='saas.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'billing_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True, verbose_name='Stripe Payment Intent ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('pending', 'Pendiente'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method_type', models.CharField(blank=True, help_text='card, bank_transfer, etc.', max_length=50, null=True, verbose_name='Tipo de Método de Pago')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de Fallo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='saas.invoice', verbose_name='Factura')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='saas.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'billing_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_event_id', models.CharField(max_length=100, unique=True, verbose_name='Stripe Event ID')),
                ('event_type', models.CharField(db_index=True, help_text='invoice.paid, subscription.updated, etc.', max_length=100, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(help_text='Datos completos del evento', verbose_name='Payload')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processed', 'Procesado'), ('failed', 'Fallido')], default='received', max_length=20, verbose_name='Estado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('error_message', models.TextField(blank=True, help_text='Si hubo error al procesar', null=True, verbose_name='Mensaje de Error')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Intentos de Reintento')),
            ],
            options={
                'verbose_name': 'Evento de Webhook de Stripe',
                'verbose_name_plural': 'Eventos de Webhook de Stripe',
                'db_table': 'stripe_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='stripe_webh_stripe__e9e10a_idx'), models.Index(fields=['event_type', '-created_at'], name='stripe_webh_event_t_c2299a_idx'), models.Index(fields=['status', '-created_at'], name='stripe_webh_status_5d33d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['stripe_invoice_id'], name='billing_inv_stripe__b8bd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subscription', '-created_at'], name='billing_inv_subscri_653b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_aefe38_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='billing_pay_stripe__7a782c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', '-created_at'], name='billing_pay_subscri_bdbd63_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='billing_pay_status_d79ab7_idx'),
        ),
    ]
