# Generated by Django 6.0 on 2026-06-24 06:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0023_creditsupportrequest'),
        ('products', '0005_add_product_selections'),
        ('tenants', '0003_create_file_resource_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('insurance_type', models.CharField(choices=[('DESGRAVAMEN', 'Seguro de Desgravamen'), ('INCENDIO', 'Seguro de Incendio'), ('VEHICULAR', 'Seguro Vehicular'), ('HIPOTECARIO', 'Seguro Hipotecario'), ('AGRICOLA', 'Seguro Agrícola'), ('VIDA', 'Seguro de Vida'), ('OTRO', 'Otro')], default='DESGRAVAMEN', max_length=20, verbose_name='Tipo de Seguro')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('coverage_type', models.CharField(choices=[('MONTO_FIJO', 'Monto Fijo'), ('PORCENTAJE_SALDO', 'Porcentaje del Saldo'), ('PORCENTAJE_MONTO', 'Porcentaje del Monto')], default='PORCENTAJE_SALDO', max_length=20, verbose_name='Tipo de Cobertura')),
                ('coverage_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Valor de Cobertura (%)')),
                ('max_coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Máximo de Cobertura')),
                ('min_term_months', models.IntegerField(default=1, verbose_name='Plazo mínimo (meses)')),
                ('max_term_months', models.IntegerField(default=360, verbose_name='Plazo máximo (meses)')),
                ('is_renewable', models.BooleanField(default=True, verbose_name='Renovable')),
                ('grace_period_days', models.IntegerField(default=0, verbose_name='Período de gracia (días)')),
                ('premium_type', models.CharField(choices=[('MONTHLY', 'Mensual (en cuota)'), ('LUMP_SUM', 'Único al desembolso'), ('ANNUAL', 'Anual'), ('BALANCE', 'Porcentaje del saldo insoluto')], default='BALANCE', max_length=20, verbose_name='Tipo de Prima')),
                ('base_premium', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Prima Base (%)')),
                ('requires_medical_exam', models.BooleanField(default=False, verbose_name='Requiere examen médico')),
                ('has_deductible', models.BooleanField(default=False, verbose_name='Tiene deducible')),
                ('deductible_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje Deducible (%)')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
                'db_table': 'insurance_insurances',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(max_length=100, verbose_name='Número de Póliza')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('total_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prima Total')),
                ('premium_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prima Pagada')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('EXPIRING_SOON', 'Por vencer'), ('EXPIRED', 'Vencido'), ('CANCELLED', 'Cancelado'), ('SUSPENDED', 'Suspendido')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('beneficiary_name', models.CharField(max_length=200, verbose_name='Nombre del Beneficiario')),
                ('beneficiary_nit', models.CharField(blank=True, max_length=20, verbose_name='NIT del Beneficiario')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('active_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='loans.activecredit', verbose_name='Crédito Activo')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_insurances', to='insurances.insurance', verbose_name='Seguro')),
            ],
            options={
                'verbose_name': 'Póliza de Seguro',
                'verbose_name_plural': 'Pólizas de Seguros',
                'db_table': 'insurance_credit_insurances',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Cobertura')),
                ('coverage_type', models.CharField(choices=[('MONTO_FIJO', 'Monto Fijo'), ('PORCENTAJE_SALDO', 'Porcentaje del Saldo'), ('PORCENTAJE_MONTO', 'Porcentaje del Monto')], default='MONTO_FIJO', max_length=20, verbose_name='Tipo de Cobertura')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Máximo')),
                ('conditions', models.TextField(blank=True, verbose_name='Condiciones')),
                ('exclusions', models.TextField(blank=True, verbose_name='Exclusiones')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='insurances.insurance', verbose_name='Seguro')),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': 'Coberturas',
                'db_table': 'insurance_coverages',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
                'db_table': 'insurance_insurers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurances', to='insurances.insurer', verbose_name='Aseguradora'),
        ),
        migrations.AlterUniqueTogether(
            name='insurance',
            unique_together={('institution', 'code')},
        ),
        migrations.CreateModel(
            name='ProductInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('premium_type', models.CharField(choices=[('MONTHLY', 'Mensual (en cuota)'), ('LUMP_SUM', 'Único al desembolso'), ('ANNUAL', 'Anual'), ('BALANCE', 'Porcentaje del saldo insoluto')], default='BALANCE', max_length=20, verbose_name='Tipo de Prima')),
                ('custom_premium', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Prima Personalizada (%)')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_associations', to='insurances.insurance', verbose_name='Seguro')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_associations', to='products.creditproduct', verbose_name='Producto Crediticio')),
            ],
            options={
                'verbose_name': 'Seguro de Producto',
                'verbose_name_plural': 'Seguros de Productos',
                'db_table': 'insurance_product_insurances',
                'ordering': ['display_order'],
                'unique_together': {('product', 'insurance')},
            },
        ),
    ]
