# Generated by Django 6.0 on 2026-06-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
        ('tenants', '0003_create_file_resource_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AddConstraint(
            model_name='insurer',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_insurer_code_per_institution'),
        ),
    ]
